# Generated by Django 3.2.8 on 2021-10-17 06:43

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211017_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=14),
        ),
    ]
