# Generated by Django 3.2.8 on 2021-10-17 06:44

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_invest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default_currency='USD', max_digits=14),
        ),
    ]
