# Generated by Django 3.2.8 on 2021-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211017_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usertype',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
