# Generated by Django 3.2.8 on 2021-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211021_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
