# Generated by Django 3.2.8 on 2021-10-21 23:20

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_usertype_email_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='btc_balance',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('2'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='eth_balance',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('2'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='usdt_balance',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('2'), default_currency='USD', max_digits=14),
        ),
    ]
