# Generated by Django 3.2.8 on 2021-11-11 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20211023_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(max_length=100)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
