# Generated by Django 3.2.8 on 2021-11-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_replys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replys',
            name='to',
        ),
    ]
