# Generated by Django 3.2.8 on 2021-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_method',
            name='Message',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
