# Generated by Django 3.2.8 on 2021-11-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_payment_method_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='email_confirm',
            field=models.IntegerField(default='0'),
        ),
    ]
