# Generated by Django 3.2.8 on 2021-11-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_invest_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='duration',
        ),
    ]
