# Generated by Django 3.2.8 on 2021-11-23 15:15

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20211123_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invest_plan',
            old_name='amount_to_currency',
            new_name='amountfrom_currency',
        ),
        migrations.RenameField(
            model_name='invest_plan',
            old_name='amount_from_currency',
            new_name='amountto_currency',
        ),
        migrations.RemoveField(
            model_name='invest_plan',
            name='amount_from',
        ),
        migrations.RemoveField(
            model_name='invest_plan',
            name='amount_to',
        ),
        migrations.RemoveField(
            model_name='invest_plan',
            name='duration',
        ),
        migrations.AddField(
            model_name='invest',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invest_plan',
            name='amountfrom',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='invest_plan',
            name='amountto',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
    ]
