# Generated by Django 3.2.8 on 2021-11-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20211123_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invest_plan',
            old_name='amountfrom',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='invest_plan',
            old_name='amountfrom_currency',
            new_name='amount_currency',
        ),
    ]
