# Generated by Django 3.2.8 on 2021-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_invest_plan_amountto'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest_plan',
            name='percentr',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
