# Generated by Django 3.2.8 on 2021-12-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_invest_plan_percentr'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_method',
            name='abrr',
            field=models.CharField(blank=True, default='BTC', max_length=100),
        ),
    ]
