# Generated by Django 3.2.8 on 2021-12-02 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_payment_method_abrr'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('pay_amount', models.CharField(blank=True, max_length=100)),
                ('confirm', models.BooleanField(default=False)),
                ('payout_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iplan', to='main.invest_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
