# Generated by Django 3.2.8 on 2021-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_investmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentmodel',
            name='payout_date',
            field=models.DateTimeField(),
        ),
    ]
