# Generated by Django 3.2.8 on 2021-12-02 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_alter_investmentmodel_payout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('trxid', models.CharField(blank=True, max_length=100)),
                ('confirm', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
